# Stubs for pika.tcp_socket_opts (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

LOGGER: Any

def socket_requires_keepalive(tcp_options: Any): ...
def set_sock_opts(tcp_options: Any, sock: Any) -> None: ...
